### ISSUE TITLE
bug: nvim-treesitter[xml] compile error

### ISSUE THREAD

**Issue by Robert4S** [tree-sitter-grammars/tree-sitter-xml#13]
### Did you check existing issues?

- [ ] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues

### Describe the bug

getting a compile error for nvim-treesitter[xml] in the scanner.c function 'string push', compiler is seeing an implicit declaration of function "max". There is a macro in the file that should define it on windows, but it doesn't seem to be doing so.

### Steps To Reproduce/Bad Parse Tree

1. Add nvim-treesitter to neovim config
2. Start neovim

### Expected Behavior/Parse Tree

I expect nvim-treesitter to compile, but it doesn't.

**Comment by ObserverOfTime** [comment]
Should be fixed with ab85469fedbf4f32da9310dd76dcedba059fc482
