### ISSUE TITLE
Filter `AttValue` with `#any-of?` 

### ISSUE THREAD

**Issue by Bno93** [tree-sitter-grammars/tree-sitter-xml#14]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.22.2

### Describe the bug

Hey Devs 👋🏻 ,

This might be more of an understanding issue that a bug, because I'm new to the tree-sitter syntax :swe. 
I'm using `tree-sitter-xml 0.6.1` alongside `tree-sitter 0.22.2` in a **rust** project. 
In which I want parse a xml file like this:

```xml
   ...
    <import>
        <module name="module1" />
        <module name="module2" />
        <module name="module3" />
        <module name="module4" />
        ...
    </import>
   ... 
```

My goal is to check if certain modules are listed which I try with this query:

```lisp
(element
    (_
        (Name) @name
        (Attribute
            (AttValue) @module_name
        )
    )
    (#eq? @name "module")
    (#any-of? @module_name "module1" "module3" "module4")
)
```

Apparently this query produces no matches. Without the `(#any-of? @module_name "module1" "module3" "module4")` I get all modules. 

I expected to Match against only the against "module1" "module3" and "module4".

thanks in advance 😄 

### Steps To Reproduce/Bad Parse Tree

see in the description 

### Expected Behavior/Parse Tree

see in the description 

### Repro

see in the description

**Comment by ObserverOfTime** [comment]
It's because `AttValue` includes the quotes.

```clojure
(element
  (_
    (Name) @name
    (Attribute
      (AttValue) @module_name))
  (#eq? @name "module")
  (#any-of? @module_name "\"module1\"" "\"module3\"" "\"module4\""))
```

**Comment by Bno93** [comment]
Worked 😄 thanks for the quick answer 👍🏻
