### ISSUE TITLE
bug: Error parsing `]` in CharData

### ISSUE THREAD

**Issue by jlcrochet** [tree-sitter-grammars/tree-sitter-xml#22]
### Did you check existing issues?

- [x] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.22.6 (b40f342067a89cd6331bf4c27407588320f3c263)

### Describe the bug

Parsing the following document
```xml
<test>]</test>
```
results in the following tree:
```
(ERROR [0, 0] - [1, 0]
  (STag [0, 0] - [0, 6]
    (Name [0, 1] - [0, 5]))
  (content [0, 6] - [1, 0]
    (CharData [0, 6] - [1, 0])))
```
Probably a false positive happening in the scanner when looking for CDATA delimiters.

### Steps To Reproduce/Bad Parse Tree

```bash
echo '<test>]</test>' > test.xml
tree-sitter parse test.xml
```

### Expected Behavior/Parse Tree

```
(document [0, 0] - [1, 0]
  root: (element [0, 0] - [0, 14]
    (STag [0, 0] - [0, 6]
      (Name [0, 1] - [0, 5]))
    (content [0, 6] - [0, 7]
      (CharData [0, 6] - [0, 7]))
    (ETag [0, 7] - [0, 14]
      (Name [0, 9] - [0, 13]))))
```

**Comment by ObserverOfTime** [comment]
Fixed in 809266e
