### ISSUE TITLE
bug: PyPi homepage is incorrect

### ISSUE THREAD

**Issue by domWalters** [tree-sitter-grammars/tree-sitter-xml#26]
### Did you check existing issues?

- [x] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [x] I have searched the existing issues

### Describe the bug

The PyPi homepage link is incorrect since this project moved:

- https://github.com/tree-sitter/tree-sitter-xml

This line needs updating to the new location: https://github.com/tree-sitter-grammars/tree-sitter-xml/blob/master/pyproject.toml#L26

### Steps To Reproduce/Bad Parse Tree

N/A

### Expected Behavior/Parse Tree

N/A

**Comment by ObserverOfTime** [comment]
PR welcome.
